const ALERT = "ALERT";
const REFETCH_MESSAGES = "REFETCH_MESSAGES";
const REFETCH_POSTS = "REFETCH_POSTS";

const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";

const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";

const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";

const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";

const ONLINE_USERS = "ONLINE_USERS";

const UNFOLLOW_USER = "UNFOLLOW_USER";

export {
  ALERT,
  REFETCH_MESSAGES,
  REFETCH_POSTS,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_JOINED,
  CHAT_LEAVED,
  ONLINE_USERS,
  UNFOLLOW_USER,
};
